---

- hosts: all
  become: true
  tasks:
    - name: install updates (CentOS)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

    - name: create vitaly user
      tags: always
      user:
        name: vitaly
        groups: root 

  
    - name: Ensure the SSH directory exists
      file:
        path: "home/vitaly/.ssh"
        state: directory
        mode: '0700'

    - name: Copy SSH Public Key
      ansible.posix.authorized_key:
        user: "vitaly"
        key: "{{ lookup('file', '/Users/vitalyshirgazin/.ssh/id_rsa.pub') }}"
        state: present
    
    - name: Add sudoers file for user vitaly
      copy:
        content: 'vitaly ALL=(ALL:ALL) NOPASSWD: ALL'
        dest: '/etc/sudoers.d/vitaly'
        owner: 'root'
        group: 'root'
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: create Svetlana user
      tags: always
      user:
        name: svetlana
        groups: root 

  
    - name: Ensure the SSH directory exists
      file:
        path: "home/svetlana/.ssh"
        state: directory
        mode: '0700'

    - name: Copy SSH Public Key
      ansible.posix.authorized_key:
        user: "svetlana"
        key: "{{ lookup('file', '/Users/vitalyshirgazin/.ssh/id_rsa.pub') }}"
        state: present
    
    - name: Add sudoers file for user svetlana
      copy:
        content: 'svetlana ALL=(ALL:ALL) NOPASSWD: ALL'
        dest: '/etc/sudoers.d/svetlana'
        owner: 'root'
        group: 'root'
        mode: '0440'
        validate: 'visudo -cf %s'

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for CentOS servers
      tags: apache,centos,httpd
      yum:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: start httpd (CentOS)
      tags: apache,centos,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Rocky"

    - name: change e-mail address for admin
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: 'ServerAdmin somebody@somewhere.net'
      when: ansible_distribution == "CentOS"
      register: httpd

    - name: restart httpd (CentOS)
      tags: apache,centos,httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest

