- name: Copy SSH Public Key
  ansible.posix.authorized_key:
        user: "vitaly"
        key: "{{ lookup('file', '/Users/vitalyshirgazin/.ssh/id_rsa.pub') }}"
        state: present

- name: openssh | generate sshd_config file from template
  tags: ssh
  template:
     src: "{{ ssh_template_file }}"
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: 0644
  notify: restart_sshd